CREATE TABLE brands (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,

    brand_code VARCHAR(50) NOT NULL UNIQUE,

    brand_name VARCHAR(100) NOT NULL,

    description TEXT,

    active BOOLEAN NOT NULL DEFAULT TRUE,

    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP
);