server:
  port:  8012

spring:
  application:
    name: product-catalog-read-service
  kafka:
    admin:
      # Automatically creates the DLT topic if it doesn't exist locally
      auto-create: true
    consumer:
      group-id: product-read-service-group

      # Reads from the beginning if a group is new, preventing data gaps
      auto-offset-reset: earliest

      # 1. IDEMPOTENCY LAYER: Disable automated background auto-commits.
      # We manually commit offsets ONLY after data is safely acknowledged by Elasticsearch.
      enable-auto-commit: false

      # 2. CONSUMER LAG & MEMORY MANAGEMENT
      # Prevents the JVM from running out of memory during a high lag catch-up loop.
      max-poll-records: 500

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    bootstrap-servers: localhost:9092
    properties:
      specific:
        avro:
          reader: 'true'
      schema:
        registry:
          url: http://localhost:8081

      # 3. REBALANCE & HEARTBEAT TIMINGS
      # If processing a batch takes too long, Kafka thinks the consumer is dead. 
      # We give it 5 minutes (300000ms) to safely write the 500 records into Elasticsearch.
      max:
        poll:
          interval:
            ms: 300000

      # Quick heartbeat checks to instantly detect absolute container death
      session:
        timeout:
          ms: 45000
      heartbeat:
        interval:
          ms: 15000

      # Tune TCP fetch thresholds for optimized payload ingestion speeds
      fetch:
        min:
          bytes: 1
        max:
          wait:
            ms: 500

      listner:
        # MANUAL_IMMEDIATE tells Spring to commit the offset to Kafka the exact millisecond 
        # we call acknowledgment.acknowledge() in our code.
        ack-mode: manual_immediate
        # Allows concurrent threads within the same container to process multiple partitions parallelly
        concurrency: 3

  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: ${ELASTIC_PASSWORD}
    connection-timeout: 5s
    socket-timeout: 60s

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    '[com.productcatalog]': INFO
    '[org.springframework.web]': INFO
    '[org.hibernate.SQL]': WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"